defaults: &defaults
  text_url: https://services-sandbox.comparaonline.com/textinator/texts/all_by_url.json
  request_timeout: 1

development:
  <<: *defaults

local_development:
  <<: *defaults

test:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

qc:
  <<: *defaults

production:
  <<: *defaults
  text_url: https://services.comparaonline.com/textinator/texts/all_by_url.json
  request_timeout: 0.6
