defaults: &defaults
  text_url: 'http://192.168.33.1:3000/texts.json'
  request_timeout: 10

development:
  <<: *defaults

local_development:
  <<: *defaults

test:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

qc:
  <<: *defaults

production:
  <<: *defaults
