defaults: &defaults
  text_url: 'http://textinator-sandbox.internal.comparaonline.com:8102/texts/all_by_url.json'
  request_timeout: 200

development:
  <<: *defaults

local_development:
  <<: *defaults

test:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

qc:
  <<: *defaults

production:
  <<: *defaults
  text_url: 'http://textinator.internal.comparaonline.com:8002/texts/all_by_url.json'
