defaults: &defaults
  text_url: 'http://52.70.90.234:8102/texts.json'
  request_timeout: 10

development:
  <<: *defaults

local_development:
  <<: *defaults

test:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

qc:
  <<: *defaults

production:
  <<: *defaults
