defaults: &defaults
  text_url: 'http://textinator-sandbox.internal.comparaonline.com/texts.json'
  request_timeout: 100

development:
  <<: *defaults

local_development:
  <<: *defaults

test:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

qc:
  <<: *defaults

production:
  <<: *defaults
  text_url: 'http://textinator.internal.comparaonline.com/texts.json'
